import hashlib

hashvalue = input("[*] the string that you want me to hash idot: ")

input("[+]m25 (press any key)")
hashobject1 = hashlib.md5()
hashobject1.update(hashvalue.encode())
print(hashobject1.hexdigest())
input("[+]sha1: (press any key)")
hashobject2 = hashlib.sha1()
hashobject2.update(hashvalue.encode())
print(hashobject2.hexdigest())
input("[+]sha224: (press any key)")
hashobject3 = hashlib.sha224()
hashobject3.update(hashvalue.encode())
print(hashobject3.hexdigest())
input("[+]256: (press any key)")
hashobject4 = hashlib.sha256()
hashobject4.update(hashvalue.encode())
print(hashobject4.hexdigest())
input("[+]sha512: (press any key)")
hashobject5 = hashlib.sha512()
hashobject5.update(hashvalue.encode())
print(hashobject5.hexdigest())
